server {
    listen 80 default_server;

    location /verify {
        proxy_pass http://127.0.0.1:5000;
        proxy_pass_request_headers on;
    }

    location / {
        proxy_pass http://127.0.0.1:5000;
    }
}
